### ISSUE TITLE
[BUG] Broken calendar in some timezones

### ISSUE THREAD

**Issue by fymmot** [Sqrrl/wc-datepicker#10]
Hi!
I received feedback from an American user that the calendar does not handle timezones and can break or give incorrect results. See issue https://github.com/fymmot/inclusive-dates/issues/42 in my repo.

For instance, if you change your local timezone to US East coast or Sao Paolo in the browser, the days of the month go missing and the date selection is incorrect. If I click October 29 the selected value will be October 28

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/6492106/213683258-1b893ab1-e3e1-4c44-99c6-48bd35721df0.png">

**Comment by Sqrrl** [comment]
Thanks for reporting. Dates are hard. 😬

Should be fixed with v0.5.1.

**Comment by fymmot** [comment]
Nice work! 
Do you think it would be possible to add timezone tests to the unit tests?
