### ISSUE TITLE
[BUG] Console error is shown if a user enters unsupported year

### ISSUE THREAD

**Issue by nasim-git** [Sqrrl/wc-datepicker#13]
**Describe the bug**
In Year field in datepicker, a user can enter the year number. If we enter invalid year number (For example: 1000000) Then a console error is being shown and the calendar is not clickable anymore even though you re enter a valid date.
There should be a boundary on maximum Year that should be used. For example: 9999?
User should not allow to enter any symbols except numbers:
-, +, etc…

**Reproduction**
1. Go to [https://sqrrl.github.io/wc-datepicker/#demo](url)
2. Change the year to 1000000
3. Open the console
4. See the js error

**Expected behavior**

**Screenshots**
[https://ibb.co/NTq67rF](url)

**Context**
I tested this on your demo.

* Device: Macbook Pro
* Operating System: MacOS
* Browser: Chrome

**Comment by Sqrrl** [comment]
Thanks for reporting. Will look into it.

**Comment by Sqrrl** [comment]
Fixed with v0.5.2.

**Comment by nasim-git** [comment]
Thanks @Sqrrl  this bug was fixed.
