### ISSUE TITLE
[QUESTION] … how to define a default range?

### ISSUE THREAD

**Issue by BenRej** [Sqrrl/wc-datepicker#14]
Hello!

I would like to know how we can define a default range to the datepicker?
I try to manage this by setting the value but it's not working.

thank you.

**Comment by Sqrrl** [comment]
Hey. You can set a range value by providing a tuple of Date objects.

```js
datepicker.value = [new Date(), new Date('01-01-2024')];
```

**Comment by BenRej** [comment]
thank you it works wonderfully
