### ISSUE TITLE
[QUESTION] Show/hide widget

### ISSUE THREAD

**Issue by Bilge** [Sqrrl/wc-datepicker#22]
There really isn't a method to show/hide the picker? Or better yet, show/hide automatically when an input receives/loses focus?

**Comment by Sqrrl** [comment]
Nope, sorry. Intentionally out of scope. I don’t want to bloat this lib by implementing specific use cases. Connecting it to an input field should be pretty straight forward. You can check the [docs page source for an example](https://github.com/Sqrrl/wc-datepicker/blob/c0dec2a222e18b56a0e6d7dd0af46cce5c674bf6/docs/index.html#L867). If you want to use it with a popover, I suggest https://floating-ui.com/.
